Doysch/reset

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/views/layouts/application.html.erb, app/views/shared/_navbar.html.erb
started the navbar and button components
=> started navbar

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
modified icons in navbar. Fixed issue displaying flex in container. Added gradient background color and hover effect on icons
=> navbar icons changed

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_select_button.scss, app/views/greenspaces/index.html.erb, db/seeds.rb
starting to get the index page formatted for responsive mobile
=> Index page formatting

app/assets/stylesheets/components/_navbar.scss
=> made navbar opaque with z index

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_radio_button.scss, app/assets/stylesheets/components/_simple_form.scss, app/views/walks/new.html.erb
=> style changed

app/views/greenspaces/index.html.erb, app/views/greenspaces/new.html.erb, app/views/greenspaces/show.html.erb, app/views/layouts/application.html.erb, app/views/walks/new.html.erb
=> added padding to every page APART from home

config/routes.rb
added routes for edit and update walks
=> created route for edit and update walk

app/controllers/greenspaces_controller.rb, app/controllers/walks_controller.rb, app/views/walks/new.html.erb
made postcode variable global so that it can be accessed in form to create a new walk
=> made postcode accessible to create walk

.gitignore, Gemfile, Gemfile.lock, app/controllers/greenspaces_controller.rb, app/javascript/controllers/index.js, app/javascript/controllers/map_controller.js, app/models/greenspace.rb, app/views/greenspaces/index.html.erb, app/views/layouts/application.html.erb, config/initializers/geocoder.rb, db/migrate/20220609133239_add_coordinates_to_walks.rb, db/migrate/20220609133922_add_coordinates_to_greenspaces.rb, db/migrate/20220609135305_rename_location_to_address_in_greenspaces.rb, db/schema.rb
created geocoder in index page
=> geocoder stablished

app/javascript/controllers/map_controller.js, app/views/greenspaces/index.html.erb
=> map finished

app/views/greenspaces/show.html.erb
link to pre walk form created in showpage of greenspace
=> Link to pre walk form

app/controllers/greenspaces_controller.rb, app/javascript/controllers/map_controller.js, app/views/greenspaces/show.html.erb, db/seeds.rb
created map in show page of greenspace
=> added map in show page

app/views/greenspaces/show.html.erb
added CSS to map in greenspace show page
=> styled map in showpage

app/views/greenspaces/show.html.erb
changed color of button show page
=> change button showpage

app/views/greenspaces/index.html.erb, app/views/greenspaces/show.html.erb
=> styled map indexpage

app/views/greenspaces/index.html.erb, app/views/greenspaces/show.html.erb
re-styled maps so that they take 100% width and increased height
=> Style map indexpage

app/assets/stylesheets/components/_card_index.scss, app/views/greenspaces/index.html.erb, app/views/greenspaces/show.html.erb
=> increased size of logo

app/assets/stylesheets/pages/_home.scss, app/views/greenspaces/show.html.erb, app/views/pages/home.html.erb
added shadow to title and changed button in show page to kill whitespace
=> added shadow title

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_card_index.scss, app/views/greenspaces/show.html.erb
=> increased width of cards

app/assets/stylesheets/pages/_home.scss, app/javascript/application.js, app/javascript/title.js, app/views/layouts/application.html.erb, app/views/pages/home.html.erb
=> added js to homepage title

app/assets/stylesheets/components/_simple_form.scss, app/assets/stylesheets/pages/_home.scss, app/views/walks/new.html.erb
changed title and ouput slider from form. Added icons
=> changed names from form, added icons

db/seeds.rb
cleaned up the photos and made them look real
=> More photos for seeds

app/assets/stylesheets/components/_simple_form.scss, app/views/walks/new.html.erb
sound label in form changed to be hidden
=> hidden sound label

app/assets/stylesheets/application.scss, app/views/pages/home.html.erb
=> description added to homepage

app/views/reviews/new.html.erb
added form to create a new review
=> added form to create a new review

app/controllers/reviews_controller.rb, app/views/reviews/new.html.erb
attempted to style form for reviews, still crappy
=> attempted to style form for reviews

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_stress_level.scss, app/controllers/reviews_controller.rb, app/controllers/walks_controller.rb, app/views/reviews/new.html.erb, app/views/walks/edit.html.erb
linked walk page to new review page
=> added link to review

app/views/greenspaces/show.html.erb
added carousel to display pics in show page of greenspaces
=> added carousel in show page greenspaces

app/views/greenspaces/show.html.erb
=> carousel style changed

app/views/reviews/new.html.erb
review form content renamed review. Dropdown added to form to show numbers 1 to 5 for review
=> review content renamed review and dropdown added to form

app/assets/stylesheets/components/_simple_form.scss, app/views/walks/new.html.erb, app/views/walks/show.html.erb
In walk show page "start reset" button deleted. Pre and post walk forms aligned vertically
=> deleted button walk show page and align both forms vertically

app/views/greenspaces/index.html.erb
fixed margin at the bottom of index page
=> fixed margin at bottom of index page

app/assets/stylesheets/components/_dashboard.scss, app/views/greenspaces/show.html.erb, app/views/layouts/application.html.erb
fixed bug displaying title in show page greenspace
=> fixed bug in show page

app/views/walks/show.html.erb
fixed the margin bottom in the walk show page
=> fixed margin bottom show walk page

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_radio_button.scss, app/views/walks/edit.html.erb, app/views/walks/new.html.erb
changed style buttons to 15px border radius
=> chenged style buttons again

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_radio_button.scss, app/assets/stylesheets/components/_select_button.scss
changed color schema of buttons and background color
=> Change color schema

app/views/pages/diary.html.erb
styled dashboards bottom and cards
=> styled dashboard

app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb
description in homepage centered
=> description homepage centered

app/views/pages/home.html.erb
=> centered text

app/views/walks/edit.html.erb, app/views/walks/new.html.erb
=> change wording of button

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_card_index.scss, app/assets/stylesheets/components/_dashboard.scss, app/assets/stylesheets/components/_radio_button.scss, app/views/greenspaces/show.html.erb, app/views/pages/dashboard.html.erb, app/views/walks/edit.html.erb
=> font fixed

app/views/greenspaces/index.html.erb
added conditional to show/hide time card depending on params[query] given or not
=> hide cards when params[query] not given

app/views/greenspaces/index.html.erb, app/views/greenspaces/show.html.erb, app/views/pages/dashboard.html.erb
This should prevent it from crashing when user enters no rating or words for review
=> changed padding to description on index AND fixed a big on review when no rating entered

app/assets/stylesheets/components/_container_show.scss, app/assets/stylesheets/components/_index.scss, app/views/greenspaces/show.html.erb
added css media queries for show page.
1) Carousel and map displayed as flex
2) reviews displayed as css grid
3) submit button added margins left and right to make size smaller
=> added media queries
